
import React, { useEffect, useRef } from 'react'
import { useState } from 'react'
import Link from 'next/link'
import axios from 'axios'
import { AiOutlineClockCircle, AiOutlineSearch } from 'react-icons/ai'
import { RxHamburgerMenu } from 'react-icons/rx'
import { IoClose } from 'react-icons/io5'

interface Book {
  id: string;
  title: string;
  author: string;
  imageLink:string;
  audioLink: string;
  averageRating:string;
}

function formatDuration(secs:number) {
  const m = Math.floor(secs/60);
  const s = Math.floor(secs % 60);
  return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
}

const SEARCH_URL = "https://us-central1-summaristt.cloudfunctions.net/getBooksByAuthorOrTitle"

export default function SearchBar() {
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<Book[]>([]);
  const [loading, setLoading] = useState(false);
  const [durations, setDurations] = useState<Record<string, string>>({});
  const wrapperRef = useRef<HTMLDivElement>(null)

  //Debounced function
  //Debounced(meaning that wait until user stop typing for x amount of time before runing a search) searching
  useEffect(()=>{
    // guard clause for checking if search box is empty or only spaces ".trim()" rmoves any spaces from the start or end
    if( !query.trim() ) { setResults([]);return;}
    setLoading (true);
    // create a timer variable to store the id(starts from 1 and increments) that is generated by setTimeout 
    // this timer can be stopped or cleared later  with clearTimeout(timer)
    const timer = setTimeout(()=>{
      axios
        //the axios.get() will expect a return an array of Book blueprint
        // (SEARCH_URL, params: { search:query } }) autoamtically generatshttps://.../getBooksByAuthorOrTitle?search=query (query state defined up top is whatever the state of query is when a user type in the searchbox)
        .get<Book[]>(SEARCH_URL, {params: { search:query } })
        
        // get() will return a response in an object "{data:[Book, Book...]}" so data is what contains our array of books
        // so then() need to reference it by storing into a param "res" to make it res.data
        //.then((res) => setResults(res.data))
        
        //we can also destructure it so we don't need to store it as a param inside params
        // this is the same as saying "const data = res.data"
        .then( ( {data} ) => setResults(data))
        
        // if we get an error then setResults([]) to revert back into empty to clear any previous values
        .catch((error)=> {console.error('Error occured: ', error);setResults([]);})
        
        .finally(()=> setLoading(false));
    },350);
    // this is the React's cleanup function that runs when everything is done before the next useEffect begins
    // what this will do is that it will stop setTimout
    return() => clearTimeout(timer)
  },[query]);

  //  Load audio duration for each result only if results arrives so it doesnt run when a user search for a query
  useEffect(()=> {
    // map is the most common but not the best because it returns an array of undefined so it requires garbage collection
    results.map((book) =>{
    //using forEach won't generate garbage and usually is best for this situation
    //results.forEach((book)=> {

      //if there is no audioLink from book or if "durations" state already have an id from book then return
      if(!book.audioLink || durations[book.id]) return;
      
      //else moving on... create a audio element using new Audio() with the audiolink
      const audioElem = new Audio(book.audioLink);
      // this adds a listener that will listen to "loadedmetadata" then will run a callback
      audioElem.addEventListener("loadedmetadata", ()=>{
        //then we wll call setDuration to update durations that will run a callback
        // it will automatically take previous old "durations" pass it into a callback then it will generate a new object and return it as a value after it formats the "audioElem.duration" from seconds into mm:ss
        // so setDuration results in  setDuration({...new}) 
        // ( I.E- setDuration({"book1": "3:04", "book2": "1:04", "book3": "3:04"}) )
        setDurations((prev)=> ({...prev, [book.id]: formatDuration(audioElem.duration)}));
      });
    })
  }, [results]);

  // Closes dropdown on outside click only
  useEffect(()=>{
    function handleClick (e: MouseEvent) {
      if(wrapperRef.current && !wrapperRef.current.contains(e.target as Node)) {
        setQuery("");
        setResults([]);
      }
    }
    //The empty dependency array [] tells React: "Only run this effect once when the component first mounts."
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  },[])

  const showDropdown = query.trim().length > 0;
  
  return (
    <div className='bg-white border-b border-[#e1e7ea] h-20 z-[1]'>
      <div ref={wrapperRef} className='relative flex items-center justify-between px-[32px] max-w-[1070px] mx-auto h-full'>
          
          {/* this is used for gap spacing to push search to right */}
          <div></div>
          
          {/* Search */}
          <div className='flex items-center w-full gap-[24px] max-w-[340px]'>
            <div className='flex items-center w-full'>
              <div className='relative w-full'>
                <input suppressHydrationWarning placeholder="Search for books" type="text" value={query} onChange={(e) => setQuery(e.target.value)} className='h-10 w-full px-4 pr-10 outline-none bg-[#f1f6f4] text-[#14px] text-[#042330] border-2 border-[#e1e7ea] rounded-lg  transition-all'/>
                {/* This is the Search Bar that shows a close icon or a search icon*/}
                <div className='absolute right-[8px] top-0 flex h-full items-center justify-end border-l-2 border-[#e1e7ea] pl-2'>
                  {query ? (
                      <IoClose
                        className='w-6 h-6 text-[#03314b] cursor-pointer'
                        onClick={()=>{
                          setQuery("");
                          setResults([]);
                        }}
                      />
                    ) : (
                      <AiOutlineSearch className='w-6 h-6 text-[#03314b]'/>
                  )}        
                </div>
              </div>
            </div>
          </div>
          {/* Hamburger Menu -mobile only*/}
          <div className='flex md:hidden items-center justify-center cursor-pointer'>
            <RxHamburgerMenu className='w-6 h-6 text-[#03314b]'></RxHamburgerMenu>
          </div>
          
          {/* This is showing the actual drop down results based on search */}
          {showDropdown && (
            <div className='absolute top-[80px] right-6 ww-full max-w-p[440px] max-h-[640px] overflow-y-auto bg-white border border-[#e1e7ea] shadow-md z-50 flex flex-col'>
               {/* display "Searching..." if it is currently loading */}
              {loading && (
                <div className='p-4 text-[14px] text-[#6b757b]'> Searching...</div>
              )}
              {/* if searching is false and no longer loading and the result is 0 then show "No Books" */}
            
              {!loading && results.length === 0 && (
                <div className='p-4 text-[14px]'>
                  No books found for "{query}"
                </div>
              )}
              {/* Assuming the first two checks are arent "passing" then  load the books in a map*/}
              {!loading && results.map((book)=> (
                // this is the link wrapper for each book generated from the array using map()
                <Link
                  key={book.id}
                  href={`/book/${book.id}`}
                  onClick={() => { setQuery("");setResults([]); }}
                  className='flex items-center gap-6 px-4 pyy-3 h-[120px] border-b border-[#e1e7ea] last:border-b-0 hover:bg-[#f1f6f4] transition-colors no-underline'
                >
                    <figure className='w-[80px] h-[80px] min-w-[80px] m-0'>
                      <img src={book.imageLink} alt={book.title} 
                        className='w-full h-full object-cover block'
                      />
                    </figure>

                    {/* Book Info */}
                    <div className='flex flex-col gap-1'>
                      <div className='text-[16px] font-medium text-'>
                        {book.title}
                      </div>
                      <div>
                        {book.author}
                      </div>
                      <div>
                        <AiOutlineClockCircle />
                        <span>{durations[book.id] ?? "..."}</span>
                      </div>
                    </div>
                </Link>
              ))}
            </div>
          )}
      </div>
    </div>
  )
}
